#!/bin/bash

pdflatex -shell-escape  main 
bibtex main
pdflatex -shell-escape main
pdflatex -shell-escape main

EXIT_STATE=$?

if [ $OSTYPE = "darwin12" ]
then	
	if [ $EXIT_STATE -eq 0 ]
	then open main.pdf &
	else echo 'Build Failed. Not opening pdf'
	fi
elif [ $OSTYPE = 'linux-gnu' ]
then
	if [ $EXIT_STATE -eq 0 ] 
	then evince main.pdf &
	else echo 'Build Failed. Not opening pdf'
	fi
fi
